services:
    sandbox_magnolia.controller:
        class: Sandbox\MagnoliaBundle\Controller\MagnoliaController
        calls:
            - [ setContainer, [@service_container] ]

    sandbox_magnolia.odm_configuration:
        class: %doctrine_phpcr.odm.configuration.class%
        calls:
            - [ setDocumentClassMapper, [@sandbox_magnolia.odm_mapper] ]

    sandbox_magnolia.odm_mapper:
        class: "Sandbox\MagnoliaBundle\Document\MagnoliaDocumentClassMapper"
        arguments:
            - 'standard-templating-kit:pages/stkSection': 'Sandbox\MagnoliaBundle\Document\Section'