services:
    sandbox_main.controller:
        class: Sandbox\MainBundle\Controller\ContentController
        calls:
            - [ setContainer, [@service_container] ]

    sandbox_main.image_controller:
        class: Sandbox\MainBundle\Controller\ImageController
        factory_service: doctrine_phpcr.odm.document_manager
        arguments:
            - @service_container
            - @doctrine_phpcr.odm.document_manager
            - @fos_rest.view_handler

    sandbox_main.debugListener:
        class: Sandbox\MainBundle\Listener\SandboxExceptionListener
        calls:
            - [ setContainer, [@service_container] ]
        tags:
            - {name: "kernel.event_subscriber"}

    sandbox_main.content_controller:
        class: Sandbox\MainBundle\Controller\ContentAdminController
        calls:
            - [ setContainer, [@service_container] ]

    sandbox_main.admin.static_editable_content:
        class: Sandbox\MainBundle\Admin\ContentAdmin
        tags:
            - {name: sonata.admin, manager_type: doctrine_phpcr, group: content, label: content}
        arguments: ["",Sandbox\MainBundle\Document\EditableStaticContent, "sandbox_main.content_controller"]
        calls:
            - [ setRouteBuilder, [ @sonata.admin.route.path_info_slashes ] ]
            # TODO: can we not hardcode this?
            - [ setContentRoot, [ "/cms/content" ] ]